### ISSUE TITLE
Script excel_picks.py should also save spreads

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#105]
Currrently, this script saves the Teams for each Game and each Players Picks. In order to be complete, it should also save the spread for each game along with which team was favored.

**Comment by blreams** [comment]
It wouldn't hurt for it to also save the scores from each game if they are available.

**Comment by jbholden** [comment]
I updated excel_picks.py to generate the favored, spread, and team scores.  Try it out to see if it meets your requirements.

**Comment by blreams** [comment]
Looks awesome. Now with two copy-n-paste operations, I can recreate the week in the scoring spreadsheet. Closing this issue.
