### ISSUE TITLE
Commissioner create_week/edit_week can create duplicate games

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#116]
I actually noticed this last week and I managed to correct it in the Admin interface before unleashing the hounds to make picks. But it happened again with one of the other commissioners this week.

Need to add something to validate the number of Games on submit from create_week/edit_week. It should also validate that Game numbers are unique and in range(1, games_per_week + 1).

**Comment by jbholden** [comment]
Is this currently causing problems on the site?  Because when I tried to
access the website, all I see is the overall and week results pages.  I
cannot access player results or enter picks page when logged in.

**Comment by blreams** [comment]
Not that I am aware. Here is a screenshot of what I see when I am on the pick10/2016/week/9/results page. Note the presence of both the Player Results and Enter Picks tabs/links.

![image](https://cloud.githubusercontent.com/assets/5880937/19709270/3839d40c-9af3-11e6-95a4-f97628aa56bf.png)

The only way this causes a problem is when a commissioner is entering the games for the week and submits multiple times with Games rearranged.

**Comment by blreams** [comment]
I believe that I have a solution for the problem of commissioner edit_week submits creating duplicate Games in the database. It can be done pretty simply in edit_week.py in the EditWeekView post() method. Once the form data is deemed valid, it is a simple matter to query and delete any existing Game objects for the year/week in question prior to saving new Game objects from the form.

**Comment by blreams** [comment]
Closing.
