### ISSUE TITLE
500 server error when Player submits picks

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#117]
This just started happening after the refactor was deployed. Basically, a Player clicks submit on their weekly picks and get a 500 on the redirect to pick10/2016/week/9/player/39/results. The picks are submitted correctly. I suspect there is something missing from an import. I tried to reproduce it locally, but it works fine. I may have to turn on DEBUG to figure it out...but that is last resort.

**Comment by jbholden** [comment]
Also, there is no longer a link to the picks (see screenshot).  If I manually go to the picks page though, I can see the enter picks page.

![screen shot 2016-10-24 at 4 10 47 pm](https://cloud.githubusercontent.com/assets/1541768/19662194/891a8c58-9a04-11e6-9340-691c9809ee30.png)

**Comment by jbholden** [comment]
Here is some code from the week_navbar.py file.  The player results page should show up unless the player id is not set.  The player id gets set if the player is linked to a player profile.  

```Python
def __show_player_results(self):
    return self.player_id != None

def __determine_player_id(self):
    profile = self.__get_user_profile()

    profile_linked_to_player = profile != None and profile.player != None

    if profile_linked_to_player and\
       self.__is_player_in_year(profile.player.id,self.year):
        self.player_id = profile.player.id
        return

    self.player_id = None
```

Can you confirm on the site that:
- a player is linked to a user profile
- that player is linked to the year 2016 (PlayerYear and Year database models)

-

**Comment by jbholden** [comment]
There is another function in enter_picks_view.py that checks if the player id is in the year.  If not, then there will be an error page shown.  Since enter picks page is working, I suspect that the player is linked to the year, but the player might not be linked to their user profile

**Comment by blreams** [comment]
It turned out to be pretty simple/stupid. The bug was somehow introduced by the refactoring I did (not surprising). However, I'm still a little confused about how it ever worked.

The problem was in pick10/player_results_view.py:
```
Ln 133:     def __get_local_time(self,utc_date,timezone_name):
Ln 134:         tz = pytz.timezone(timezone_name)
Ln 135:         return utc_date.astimezone(tz)
```

As you can see, the library pytz is called for here, but never imported. It wasn't imported before the refactor either. I suspect (hence my confusion) that a previous `... import *` must have imported it indirectly. Then, when I removed the `import *`, pytz was no longer available and resulted in an exception. 

I guess that reinforces my view that it is dangerous to use `import *` in a script. It is a nice shortcut when typing commands at the command line. But, IMHO, in a script it is better to do explicit imports. That way you always know where an object comes from.

The other thing that bothers me is that I was not able to reproduce this on my local server. To that I can only speculate that it has to do with the timezone of the deployed server vs. my local server. Unless something actually called `__get_local_time()`, it would not have manifested.

I fixed the code on the deployed server. Once I commit/push, I will close this issue.

**Comment by jbholden** [comment]
I still don't see the enter picks link and player results link.  Do you see it on your page?

**Comment by blreams** [comment]
No I don't...that seems like a new Issue.

**Comment by blreams** [comment]
Closing. I will create a new Issue for the missing enter picks/player results links.
