### ISSUE TITLE
Every model should have a unique id key

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#125]
This will not happen until the off-season because it involves a db structure change.

In preparation for creating a db backup/restore strategy, I think it will be necessary for each model to have a unique key, and I would like to standardize on id as the field name for that key. Some models already have it.

**Comment by jbholden** [comment]
Are you suggesting to override the functionality that automatically sets the id field to a unique value when creating a model instance?

[https://docs.djangoproject.com/en/1.10/topics/db/models/#automatic-primary-key-fields](url)

Why is overriding this value required to backup/restore correctly?

**Comment by blreams** [comment]
That's right, I forgot that django automatically adds the id field.

It might be necessary to specify the id when restoring models from a backup.

**Comment by blreams** [comment]
Going to close this issue.
