### ISSUE TITLE
Player model, what fields do we need?

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#15]
Currently, the Player model has two fields (public_name and private_name). In my rush to get usable data from the spreadsheets into the models, I arbitrarily decided to put the name from the spreadsheet (ie. "Holden, Brent") in public_name. Then I split this into first/last name and created the string that goes in private_name using "last_first" (ie. "holden_brent").

As I said that part was all very arbitrary.

I think it makes sense to have public_name and private_name fields in the Player model. We need that because every Player (whether they are a registered User or not) will have to be displayed in the pool views (so you can't keep that information in the UserProfile).

Let me suggest the following:
  1. Let's keep the public_name and private_name fields.
  2. Entries in public_name must be unique (no two players may share the same public_name).
  3. Entries in private_name must be unique (no two players may  share the same private_name).
  2. Let's add an optional field, ss_name, that will hold the player name from the spreadsheet. 
     That way I don't have to do anything arbitrary when loading history from spreadsheets.
  3. Registered Users should have a way to modify public_name and private_name.
  4. Registered Users cannot change ss_name.
  5. Registered Users that are new (don't have spreadsheet history) will not have anything in
     ss_name.

What do you think about the above list? 
Is there anything else needed in Player model?

**Comment by jbholden** [comment]
My thoughts on the public name is that it should not show the last name (unless explicitly changed by the User to show it).  That way untrusted people who visit the site would not be able to extract the full names of everyone in the pool.  In the google app engine version, I hid the last name by just using the first one or two letters of the last name (i.e. Brent H.).  Some names were not unique so I had to use 2 letters from the last name.

I think that the private name could show the full name to logged in users.

I don't know of anything else to add to the Player Model.

**Comment by blreams** [comment]
Closing this issue. To summarize, items 1 through 7 above are still applicable. In addition there are the following items:

8. private_name will be the first name, last name and optional digits to make it unique.
9. public_name will be first name and optional letters from last name (and digits if necessary) to make it unique.

I updated the wiki entry for the Player model.
