### ISSUE TITLE
Does Game model need a winner field?

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#17]
I know we have all the info we need to determine the game winner for a particular game, but would it make it easier on the views if we had a winner field (integer), where 1 means team1, 2 means team2 and 0 means game is not complete?

**Comment by jbholden** [comment]
I'm ok with a winner field.  Would this be the winner according the spread, winner according to the score, or fields for both?

**Comment by blreams** [comment]
I added a winner field to the Game model. This is the winner according to the spread. Closing this issue.
