### ISSUE TITLE
stage_history populate_games_for_year_week() doesn't set game state

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#19]
I believe that the following code in stage_history.py does not specify the game state.  I believe it should be set to 3, which is FINAL.  As a result, the game state gets set to 0 by default which is INVALID.

```Python
def populate_games_for_year_week(yearnum, weeknum):
   ...
   gameobj = Game.objects.get_or_create(week=weekobj, gamenum=gamenum, team1=team1obj, team2=team2obj, team1_actual_points=team1actualpoints, team2_actual_points=team2actualpoints, favored=favored, spread=spread, winner=winner)
```

**Comment by jbholden** [comment]
There is a fix for this in the calculator pull request.  If you don't want to incorporate this code then another fix needs to be submitted.

**Comment by blreams** [comment]
I merged the calculator branch into master, so I picked up your change to stage_history.py. I am closing this issue.
