### ISSUE TITLE
Unregistered users from past years

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#2]
I wasn't sure if you planned on loading past years data into the database or to just start fresh from the current year.  If you did want to load data from past years, I was curious as to how to add users that have not been registered.

* Would you create a UserProfile model for each user even if they were unregistered?
* Once a user tries to register, would it try to match existing users in the database?
* Would you create a different model like Player?  It seemed to me like you were trying to get away from the Player model
* Any other ideas?

I am trying to figure out where to start adding some code to the project.  I thought as a first step it would be good to load players from a excel spreadsheet into the database through some sort of REST API call.

**Comment by blreams** [comment]
I was planning to load all the data from past years. In fact I modified the spreadsheets (that have all been committed) to get rid of various anomalies in the data (like teams that were specified using different strings...think Mississippi State vs. Miss St. vs. Mississippi St., etc). I also made sure that all players used the same player name in that past spreadsheets. Finally, I also transferred the data from 1997, 1998 and 1999 to spreadsheets like 2014 so the data for those years could be algorithmically accessed the same way from any year. There may still be some anomalous data left in the sheets though.

I think what i want to do is to create a UserProfile for every user that has ever played the game. Give each one a unique password that can be determined by admins from their username. Then provide a way for current players to change their password. That way each current user is already "registered". Later we can put code in that will force a user to change their password based on a flag that is initially set.

Where can you start? Well, I've been slowly working on getting stage_history.py to totally recreate the history of the pool from 1997 to the present (by pulling data from the spreadsheets). I'd start with 2014 and work my way backward.

Have you looked at pick10/models.py to make sure the classes are setup correctly?

**Comment by blreams** [comment]
I'm going to close this issue, as I think all of the relevant questions raised have been addressed either here or in other Issues.
