### ISSUE TITLE
Loading a player that defaults in a week

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#21]
In the excel spreadsheet, a defaulter is recognized by not entering a tiebreak score.  However, in the spreadsheet a defaulting player will have picks for the games (dummy values that are something like _D_).

When stage_history.py loads the picks for a defaulter, for each pick it will set the winner field based on the dummy filled in values from the spreadsheet.

My code in calculator.py detects a defaulter by the Pick.winner field being 0, not a valid value of 1 or 2.  I think that stage_history.py should set the Pick.winner field to 0 for all the picks in a week where the player defaults.  

The excel spreadsheet script pool_spreadsheet.py provides a function called did_player_default() that can be called to detect a defaulter in a week.

The following line in stage_history.py could be changed to check for a defaulter.
```Python
def populate_picks_for_year_week(yearnum, weeknum):
   ...
   winner = 1 if pick.winner == 'team1' else 2

```

**Comment by jbholden** [comment]
I made the following fix in the branch week_results_1 stage_history.py.  You can decide to accept it or not.

```Python
if poolspreadsheet.did_player_default(pick.player_name,weeknum):
     winner = 0
else:
     winner = 1 if pick.winner == 'team1' else 2
```

**Comment by blreams** [comment]
I merged the changes to stage_history.py from the branch week_results_1. That merge was pushed to origin/master, so I don't think we need that branch anymore. However, I was scared to delete it. I will leave it to you to delete that branch.

**Comment by jbholden** [comment]
I went ahead and deleted the branch.
