### ISSUE TITLE
Conference division not being set consistently

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#22]
stage_models.py populate_conferences_teams() and stage_history.py populate_team() are not setting the Conference division field the same way for Conferences without divisions.  

* populate_conferences_teams() does not set the division which results in the value of None. 
* populate_team() sets the division to ''.  

This causes problems when populate_team() is called because it does not find an existing division and creates a new one, resulting in multiple Conferences and teams with the same name.

**I will try and explain what my code is doing.**

I have been calling the following functions in the following order
```Python
stage_models.py: 
populate_conferences_teams()    # sets up teams and conferences with division=None

stage_history.py:
main()  # load some year or week
populate_team() called within main()   # if conference or team doesn't exist, creates a new one
```

This is the code for populate_team and an example that fails
```Python
def populate_team(teamname):
    mascot, conference, division = team_mascot_conference_division[teamname].split(':')
    confobj, create = Conference.objects.get_or_create(conf_name=conference, div_name=division)
    teamobj, create = Team.objects.get_or_create(team_name=teamname, mascot=mascot, conference=confobj)

# for 'Navy" which has no division, team_mascot_conference_division['Navy'] is set as follows:
'Navy': 'Midshipmen:Independents:'

# the result is the following, notice that division is set to '', not None
mascot, conference, division = team_mascot_conference_division[teamname].split(':')
mascot = 'Midshipment'
conference = 'Independents'
division = ''

# the earlier call populate_conference_teams() created a Conference with the following value
Conference.conf_name = 'Independents'
Conference.div_name = None    # notice the None value here

# the call to populate_team() then does not find an existing conference because division is ''
# the existing conference has a division value of None
# as a result a new Conference is created here instead of finding the existing one
confobj, create = Conference.objects.get_or_create(conf_name=conference, div_name=division)

# as a result of the new conference, a new team gets created as well even though one already exists
# this is because the confobj is different
teamobj, create = Team.objects.get_or_create(team_name=teamname, mascot=mascot, conference=confobj)


```

**Comment by blreams** [comment]
Did you already fix this in one of the branches that I merged?

The reason I ask is because I see this code in stage_history.py:

```python
def populate_team(teamname):
    mascot, conference, division = team_mascot_conference_division[teamname].split(':')
    if division == '':
        division = None
    confobj, create = Conference.objects.get_or_create(conf_name=conference, div_name=division)
    teamobj, create = Team.objects.get_or_create(team_name=teamname, mascot=mascot, conference=confobj)
    return teamobj
```

From that it looks like the empty string for division is being replaced by None in the team object.

If that is the sum total of the fix, then we can close this issue since that change got merged to master.

**Comment by jbholden** [comment]
I made a fix to make forward progress and it seems to work.  I guess the question is do you want Independents to have division equal to '' or None.  This sets it to None.  We can close it if you concur with None.

**Comment by blreams** [comment]
It probably makes more sense for an empty division to have the value empty string rather than None. That way you don't have to do anything special if you want to print the conference and division.

**Comment by jbholden** [comment]
To use an empty string, I believe the following changes should be made.

1.  Remove the above change
2.  Edit the following code in pick10/models.py by changing to div_name='' in the passed in parameter

```Python
def add_conference(conf_name, div_name=None):
    c = Conference.objects.get_or_create(conf_name=conf_name, div_name=div_name)[0]
    return c
```

3 . Also in pick10/models.py, do we want to add a default='' parameter to div_name?

```Python
class Conference(models.Model):
    conf_name = models.CharField(max_length=40)                            # Conference name, 'Southeastern'
    div_name = models.CharField(max_length=40, null=True, blank=True)      # Division name, 'East'
    ...
```

**Comment by blreams** [comment]
I made the suggested changes. NOTE: when you pull this change, you will need to migrate your existing DB using "python manage.py migrate".
