### ISSUE TITLE
Need Help Running Functional Tests

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#23]
I'm not exactly sure how to get PhantomJS to work with the functional tests.
I downloaded PhantomJS and added the executable to the PATH variable.

```
# I run this command
python manage.py test functional_tests

# I get this error
WebDriverException: Message: Can not connect to GhostDriver
```

Can you provide guidance on the steps you use to run the functional tests.  Thanks.

**Comment by blreams** [comment]
I've had mixed success with PhantomJS. It seems to work pretty well on my linux server, but it doesn't work so well in my cygwin environment under Windows (which is where I do most of my development). For the time being I just punted on Functional Tests.

**Comment by jbholden** [comment]
I have been using the Firefox browser for functional tests and that works pretty well on my Mac OSx.  I keep changing the functional_tests/base.py to firefox for my tests.

**Comment by blreams** [comment]
We could have both and select which one to use from an environment variable. That way you wouldn't have to manually change code each time you git pull.

**Comment by jbholden** [comment]
That sounds like a good idea.

**Comment by blreams** [comment]
I'm going to close this issue as I have committed a fix to master that allows you to configure which webdriver to use in functional tests via the environment variable:

```
export COLLEGEFOOTBALLPICK10_SELENIUM_WEBDRIVER = 'firefox'
# or,
export COLLEGEFOOTBALLPICK10_SELENIUM_WEBDRIVER = 'phantomjs'
```

Link to Issue #64
