### ISSUE TITLE
Where to put CSS files

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#24]
Is there a directory where the CSS files should go?  It doesn't seem like there is a directory like "static" created yet for CSS files.

**Comment by jbholden** [comment]
Looks like in the settings.py file it specifies the directory as /static.  It just hasn't been created yet.  Please confirm this is the right location for CSS files and close this issue.

**Comment by blreams** [comment]
If I remember right, django has two settings that relate to static files. The first is STATIC_FILES_DIRS which is a list of full paths to directories that contain static files. It is set relative to the top level directory and is called "./static". The other tells django where static lives in the URL path (STATIC_URL = "/static/").

Basically, you can create a directory called "static" parallel to manage.py. I think you can put all the static files there, or in directories inside there.
