### ISSUE TITLE
Is College Football Pick 10 title temporary or permanent?

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#25]
Here is a preliminary screenshot of the week results (using branch week_results_1).  

![screen shot 2015-07-27 at 2 27 07 pm](https://cloud.githubusercontent.com/assets/1541768/8914197/e543bb80-346b-11e5-815b-ee3581f32698.png)

The text "College Football Pick 10" is defined in the base.html template as follows.
```HTML
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        {% block side_block %}{% endblock %}
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div>
          <h1 id="base_id">College Football Pick 10</h1>
          {% block body_block %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
```

is this text a temporary placeholder or did you plan on showing it on every page?  I think the text is redundant since Pick10 is already shown in the top left of the screen.

**Comment by blreams** [comment]
Perhaps we should change the Pick10 link on the left side header to Home. But I do think I want College Football Pick 10 to appear as the title on every page.

**Comment by jbholden** [comment]
Ok, it will show up on every page.
