### ISSUE TITLE
New User Management

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#26]
I recently submitted a change in the branch week_results_1 that shows the private names if the user has logged in.

/pick10/week_results_view.py
```Python
use_private_names = request.user.is_authenticated()
```

This got me thinking that anyone who registers with the website would then be able to see the private names, even if they were a malicious user.  Is there some sort of approval process that the site administrator uses to approve new users, and as a result approve them to view the private names and other secure site features?  Is there something else to check besides an authenticated user?

**Comment by blreams** [comment]
I'm not too concerned about malicious users registering with the site. While it may happen, the worst they can do is view the pool results. They can't submit or change picks. If it gets to be a problem, I suppose the Admin can manually cull the User model of registered Users that aren't recognized.

Tell me if this is how we want to handle this situation?:
  * Non-registered site visitors can only see the home page and can either login or register.
  * Registered (but not Active) site visitors who have logged in can view public views of the pool and pool history. But they cannot make or edit picks.
  * Active site visitors who have logged in can view private views of the pool and pool history. They can make and edit picks for the current year within the pool rules.

**Comment by jbholden** [comment]
I think this sounds reasonable.  How do you determine if a user is active or not?  Is this just the email confirmation or some special thing to check, like is a user linked to at least one Player?

**Comment by blreams** [comment]
An active user is one that has paid the entry fee and that would necessarily be linked to an email address or private name. Changing a player to "active" will be a manual step that the Admin does when payment is received.

**Comment by jbholden** [comment]
I'm not exactly clear on how the user will be linked to an email address or private name.  Should it be linked to a Player model instead of a private name?

Would the process work something like this?
```
1.  User registers with the site to create an account
2.  Once payment is received, the admin creates a new Player object or uses an existing one
3.  Admin creates a new PlayerYear that links to this Player object.
4.  Set the user's UserProfile.player field to this Player object
```

Then the following access control code would be something like
```
private_access =  user logged in and user's profile player field is linked to a Player
public_access = user logged in
visitor_access = not user logged in
```

With this method, any participant from a past year could view the private names even if they were not signed up for the pool this year.

Also, were you planning to have a field to indicate if payment was received?  Or could a PlayerYear object's existence for a particular year indicate this?

**Comment by blreams** [comment]
I believe that what you have written above is essentially correct. Let me clarify a few things.

```
1. User registers with the site to create an account.
2. The Admin will either create a new Player object or use an existing one (regardless of payment).
3. Set the user's UserProfile.player field to this Player object.
4. Once payment is received, Admin creates a new PlayerYear object that links to the Player object.
```

I agree with your summarization of access control code.

To answer your last question, the existence of a PlayerYear object should be sufficient for determining if payment was received because this object is only created after payment is received.

**Comment by blreams** [comment]
I'm going to close this Issue because I think we have come to agreement on how it is to be handled.
