### ISSUE TITLE
Google App Port to Django

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#27]
I have been porting the code from the google app version to the Django version.  I don't know if you plan on writing your own code and user interface, but I expect this code will be good enough for this year's pool.  You can change it later if you want.

The code will do the following:
* display overall results
* display weekly results
* display player's results for a week
* display tiebreaker information
* allow game scores to be updated

Right now, only the week results code is showing up on the website (branch week_results_1).  Since the 2015 pool will be starting soon, I think I will try and just port the code with minimal tests.  The code was already tested on the Google App so it should work ok.  Then I plan to add in the testing later.

Let me know of any issues or concerns.

**Comment by blreams** [comment]
Since I merged the branch week_results_1 and recreated my 2014 database from the spreadsheets, it seems to be working.

**Comment by jbholden** [comment]
The player results is also working now.  I haven't merged the player_results branch yet.  I'm working on overall results now, but it is kind of slow (I think memcache could be used to speed it up)

**Comment by jbholden** [comment]
There are currently pool requests that satisfy all of the functionality mentioned above.  I still would like to do the following:
* use memcache to speed up overall results
* fix the pages to to check the logged in user as reported in #26 
* add some sort of link to switch between years in the sidebar (can be temporary until final solution determined)
* write new tests andr copy tests from the google app version

**Comment by jbholden** [comment]
There are multiple pull requests available to pull in the code.  Please look at it when you get time.  They were created in the following order:

* player_results
* overall_results
* tiebreak
* update games
* week links
* year links

Also, here are a few slides I put together

![screen shot 2015-08-08 at 3 43 30 pm](https://cloud.githubusercontent.com/assets/1541768/9151959/90f315c6-3de4-11e5-9f50-c6ae82185d64.png)

![screen shot 2015-08-08 at 3 43 40 pm](https://cloud.githubusercontent.com/assets/1541768/9151961/92d1a272-3de4-11e5-88ba-ac8d097f6017.png)

**Comment by jbholden** [comment]
All of the functionality mentioned above has been implemented and merged into the master.  I'm closing this issue.
