### ISSUE TITLE
User Interface Clarifications

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#28]
I had a few questions about your intentions for the user interface.

![screen shot 2015-07-28 at 3 07 17 pm](https://cloud.githubusercontent.com/assets/1541768/8940898/80c2fb38-353a-11e5-82c6-bed26fcfc9ca.png)

**"Home" link**
The "Home" link in the top bar on the right takes you to the /pick10 home page.  What is your intention to show on this page?

**"Pick10" link**
The "Pick10" link on the top bar on the left takes you to the Pick10 index page.  What is your intention to show on this page?

**Top bar checkbox**
In the bar across the top, there is a checkbox right next to the "logged in as brenth" text.  What is this for? 

**Sidebar**
What do you intend to put on the sidebar?  Links to different years and weeks?

**Years and Weeks Information**
In the google app, the top of the page looks like this

![screen shot 2015-07-28 at 3 12 38 pm](https://cloud.githubusercontent.com/assets/1541768/8941016/20363a40-353b-11e5-8738-c25614272984.png)

Where do you plan on putting the links to switch between weeks and years?  Should I copy something similar to the google app interface to put at the top of the html template body_block?  Or should this go in the sidebar?

**Comment by blreams** [comment]
This isn't currently what is implemented, but this is what I had envisioned:


**"Home" Link**
I was thinking that this would be the landing page. It wouldn't show anything in terms of actual pool results. You wouldn't have to be logged in to view this page. It would have a Pick10 link which would reguire you to login, and take you to the pick10 index page.

**"Pick10" Link**
A more informative landing page for the pool (it might show some high-level pool stats like number of participants, the current week, the leader, the last weekly winner, etc.

**Top bar checkbox**
Actually this is not a checkbox, it is supposed to be a rollup of the top nav when you view on a small form factor screen. I must confess that I don't really know what I am doing with bootstrap, but this is something that bootstrap has created.

**Sidebar**
The sidebar should contain links to previous years...that's good enough for now.

**Years and Weeks information**
I'm OK with doing it the way it was in the google app. We can always change it later.

I also toyed with the idea of having a link to the admin interface, but I think it is best if that is left as something where only those with a need-to-know will know how to get to it.

**Comment by jbholden** [comment]
**Top bar checkbox**
On my system it shows up as a checkbox on Safari, but on Firefox seems to be some kind of menu. 

**Sidebar/Years And Weeks Information**
I was thinking about putting the weeks information in the sidebar, but it might be easier to just copy the google code for now.

**Comment by jbholden** [comment]
I created an issue for the checkbox anomaly (#49)
I am closing this issue.
