### ISSUE TITLE
How to access user profile?

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#29]
I'm not sure that a UserProfile is being created for a user anymore in the code.

The following submit
https://github.com/blreams/collegefootballpick10/commit/3358f0438b18c91f64d6c940388e133f69f155d3

 removed the following line from pick10/models.py
```Python
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])
```

Is the user profile still being created, and how is it accessed?

**Comment by blreams** [comment]
I was trying to make that code work, where the registration form had the additional profile fields to enter. But it isn't working <sigh>.

**Comment by jbholden** [comment]
Why not create a "edit_profile.html" form that allows editing a User's profile.  You can redirect to this page after activation is complete.  (maybe a javascript redirect in the activation_complete.html template after 30 seconds?)

Also, were you planning on having an admin assign the player field or let a user choose a Player?
If the admin assigns the player field, then only the company and preferredtz needs to be entered in the edit_profile form.

```
class UserProfile(models.Model):
    player = models.OneToOneField('Player', blank=True, null=True)
    company = models.CharField(max_length=50, blank=True)
    preferredtz = models.CharField(max_length=100, null=True, blank=True, choices=tz_choices)
```

**Comment by blreams** [comment]
IMO, only the admins should be allowed to link a Player object to a particular User. Now, a User cannot participate in the pool, only a Player can do that. Which means that until a User has been linked to a Player, the User cannot participate. The admins will decide whether to link each activated User to an existing Player or create a new Player.

For now, I don't think we need to do anything special in terms of providing an interface to do that. I think the admins can just use the admin app to make that connection (or create a new Player and then make the link).

In the future it might be nice to provide a more bullet-proof way to do that. Something like special URLs to administer User/Player links. It would need to handle the following situations:
  1. Link an existing Player to a User (only works if User's Player is None)
  2. Link a new Player to a User (only works if User's Player is None)
  3, Remove the Player link from a User (only works if User's Player is not None)

**Comment by blreams** [comment]
As for the UserProfile, I'm thinking that we want a link in the navbar to allow a User to set/change their UserProfile. And as you said, the form only needs to set the company and preferred tz.

**Comment by blreams** [comment]
I generated a pull request (branch userprofileform #46) that has code to allow Users to create/update their UserProfile. I'd like for you to check it out and comment. Let me know if you think this is sufficient and I will merge it back into master.

**Comment by jbholden** [comment]
I think it is fine.  I already merged it with the master.

**Comment by blreams** [comment]
I think we've bottomed out on this issue. I will close it.
