### ISSUE TITLE
models.py analysis

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#3]
As suggested in #2, I will take a look at models.py and compare it to the google app engine models used from last year and some other suggestions.  You might want to go thru this list and see if you approve/disapprove.  I am going to create a separate post for each model class.

**Comment by jbholden** [comment]
UserProfile class addition summary
```
1. "years" field indicates what years the user participated in
2. public/private/handle name
3. alternate email address and payment email address
4.  timezone preference
5.  years paid to indicate if a player has paid the entry fee
6.  approval flag to approve user entry into a pool for a year
```

For the user class, I looked at the Player model in google app engine and the following issue:
https://github.com/jbholden/cdcpool_google/issues/11

**years**
The google app engine Player model had a field to indicate which years the user participated in.  This was a list of integers.

**public/private/handle name**
This has to do with what name appears on the website reports.  A public name would be the name shown if no user is logged in.  A private name is the names shown to a logged in user.  In the github issue referenced above, you mentioned a handle field.  How do you want to handle what names are shown on the reports?

**email addresses**
In the github issue referenced above, an "alternate email address" and a "remote payment email address" were mentioned.  Do still want these fields?

**timezone preference**
In the github issue referenced above there was mention of a timezone preference

**years paid**
In the github issue referenced above there was mention of a years_paid that is a list of years that a user has paid the entry fee for.  This would be used to ensure entry fees were paid

**approval flag**
In the github issue referenced above there was mention of some sort of admin approval of a user that has registered for participation in year.  Once a user signs up for a year, then the admin somehow approves this user for participation.  Does this seem reasonable?  Maybe the "years" field above could be used for this.  A flag might be needed to track requests for the admin to look at (or some other method)

**Comment by jbholden** [comment]
Game model
```
1.  spread as float
2.  date field for game start time
```

**spread**
Shouldn't the "spread" field be a float instead of integer?  Spreads are usually expressed in halves (0.5)

**start date**
I found it nice to display the game start time on the game result pages for games that had not yet started.  This field was called "date" in the google app engine model and was a DateTimeProperty()

**Comment by jbholden** [comment]
Week Model

**lock_picks type**
should lock_picks be a DateTimeField or a boolean field?  If it is a boolean field, then an admin will have to manually change this value at kickoff or some deamon process would have to set this field at a particular time.  If this is a DateTimeField, then the picks would automatically get locked at this given time.  

**lock_picks deadline clarification**
The comment for lock_picks says "# Once the first game kickoff occurs, update to True"
Are you planning on allowing picks up until kickoff or at the normal 4 PM Thursday deadline?

**Comment by jbholden** [comment]
UserProfile model user state

I found in this issue a comment about user state:
https://github.com/jbholden/cdcpool_google/issues/20

```
I was thinking that each player would have a "state" (signed up, paid up, etc.). 
This would help the commissioners to see who has signed up to participate and 
who has actually paid. Then, if they aren't paid, they wouldn't show up in any of 
the reports. Right now each row of the Player table is a player/year, correct? 
So this "state" would only apply to a particular player/year combination.
```

Do you want to add a user state to the UserProfile model?  It would have to be unique to each year

**Comment by jbholden** [comment]
UserProfile model registered

When loading users from the excel file, UserProfile should somehow indicate that the user has not registered yet.

```
Option 1:  Add a boolean flag called something like 'registered'
Option 2:  Use the django User.is_active flag?
Option 3:  something else?
```

**Comment by blreams** [comment]
Any chance we can discuss each model in a separate issue (rather than just multiple posts in a single issue)? I think if we create separate issues for each, we can close them as they are adequately resolved, whereas I'm not sure we will ever resolve all of the questions in these posts. And even if we did, it is not easy to go back and figure out what the resolution was.

**Comment by jbholden** [comment]
Do you want a separate issue for each possible attribute field (for example, change Game.spread to a  float) or each model (entire Game model discussion)?

**Comment by blreams** [comment]
Probably best to do it for each attribute field "change". That way once the change has been made the issue can be closed.

**Comment by blreams** [comment]
I think all of these have been captured in subsequent Issues. I'm going to close this Issue.
