### ISSUE TITLE
Game model quarter and time_left default value 

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#33]
models.py defines the default value for Game quarter and time left as follows:

```Python
class Game(models.Model):
   ...
    quarter = models.CharField(max_length=3, default='1st')                 # Used to indicate game progress ('1st', '2nd', '3rd', '4th', 'OT')
    time_left = models.CharField(max_length=10, default='15:00')            # Time left in the quarter (MM:SS)
```

Shouldn't the default be a empty string ('') instead of 1st and 15:00?  These fields only have meaning when a game is in progress.  A game that has not started or is final has no quarter or time.

**Comment by blreams** [comment]
Agreed. Committed. Closed.
