### ISSUE TITLE
Javascript code using jquery needs to be after jquery loaded

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#37]
At the end of the template/base.html file is the following

```HTML
<!-- Bootstrap core JavaScript
  =========================================================== -->
  <!-- Placed at the end of the document so that pages load faster -->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
  <script src="http://code.jquery.com/jquery.min.js"></script>
  <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
  <script src="http://getbootstrap.com/assets/js/docs.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>
```
I have some code that is using jquery, but it fails because it is included before the inclusion of the jquery js file.  Can the jquery include be moved to the beginning of the <body> or create another block after inclusion so that the code can run after this include?

```HTML
<!-- Bootstrap core JavaScript
  =========================================================== -->
  <!-- Placed at the end of the document so that pages load faster -->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
  <script src="http://code.jquery.com/jquery.min.js"></script>
...
{% block script_block %}{% endblock %}

</body>
</html>
```

**Comment by blreams** [comment]
Let's go with the script_block as you have shown rather than changing the position of where the jquery code is included. The reason is that bootstrap has boilerplate code for including jquery and it is easier to cut-n-paste it for changes if we leave it as is.

**Comment by jbholden** [comment]
There is a fix for this in the memcache branch.  templates/base.html was updated.

**Comment by blreams** [comment]
Since I merged the memcache branch into master and it included the above fix, let's call this closed.
