### ISSUE TITLE
Memcache for speed up

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#39]
Since the overall results page has been taking about 30 seconds to calculate, I used the memcache to speed it up.  I have created a branch called memcache and created a pull request for it.

Following the instructions from https://docs.djangoproject.com/en/1.8/topics/cache/, I setup the memcache to use a table in the database and it seems the work well.

You have to run the following command to setup the table
```
python manage.py createcachetable
```

The memcache copy of the overall results gets updated when the scores are updated in the update games page.  Here are a few slides about the design.

![screen shot 2015-08-08 at 3 53 44 pm](https://cloud.githubusercontent.com/assets/1541768/9151985/b9c3cf62-3de5-11e5-92f7-1b38e60186dd.png)

![screen shot 2015-08-08 at 3 53 51 pm](https://cloud.githubusercontent.com/assets/1541768/9151986/bc5081bc-3de5-11e5-9f9e-5e82c5d53f15.png)

![screen shot 2015-08-08 at 3 53 58 pm](https://cloud.githubusercontent.com/assets/1541768/9151987/be3e5990-3de5-11e5-8e73-c6c98876eaaf.png)

![screen shot 2015-08-08 at 3 54 05 pm](https://cloud.githubusercontent.com/assets/1541768/9151988/bffe5d20-3de5-11e5-901f-fbbad5f025ab.png)

**Comment by blreams** [comment]
You can close this issue, but that is awesome documentation. Might want to move that to the wiki.
