### ISSUE TITLE
User Model Clarification

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#4]
I have been trying to use the rest-framework model (see http://www.django-rest-framework.org) to create an API to allow Users to be added.  However, I have not yet figured out how to get the serializer to work with the User model and UserProfile model.

Can you explain the following code from models.py?  I understand the UserProfile class, but I am not sure what the last statement is doing.  I think it is adding a profile attribute to the User Model.

```Python
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    company = models.CharField(max_length=50, blank=True)

# what does this do?
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])
```

Given this code, how would you go about creating a User?  Specifically, I am struggling with setting the profile field.  I think method 2 might be the right method, but I cannot get the user.profile.company method to set a value other than ''
```
# create a user method 1?
user = add_user(username, email, firstname, last name)
user_profile = UserProfile.objects.create(user=user,company='Intel')
user.profile = user_profile
user.save()

# create a user method 2?
user = add_user(username, email, firstname, last name)
user.profile.company = 'Intel'
user.save()

# something else?
```

**Comment by blreams** [comment]
After playing around with this in the shell a bit, I figured out that your latter method was close, but lacked one thing. Here is the correct way to do this:
```
# create a user method 3
user = add_user(username, email, firstname, lastname)
user.userprofile.company = 'Intel'
user.userprofile.save()   # This was the thing you were missing
user.save()
```

Also, the lambda function way of referencing the profile was something I got from an older version of django, that isn't needed anymore. I cleaned up a few things related to UserProfile along with adding it to the admin (you can see and set company now when you view a particular user). Now that this is working, we can change UserProfile to suit our needs.
