### ISSUE TITLE
Need to cache both public and private views of results pages

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#42]
If a user is logged in, the results should be the private view. If a user is not logged in, the results should be the public view. Both views need to be cached.

**Comment by jbholden** [comment]
Both views are being cached, however, I cannot add the code to detect which to display until the UserProfile gets implemented.

* if user not logged in, prevent access to page
* if user logged in but no player, show public
* if user logged in and linked to player, show private results  (need to access UserProfile)

**Comment by blreams** [comment]
UserProfile is already in the model and you can create new UserProfile objects via the admin interface. I'm working on the form submission that a User will use to update their UserProfile. But there will not be anything to require a User to update their profile. I don't want to go into any more detail here since Issue #29 is already tracking that.

**Comment by jbholden** [comment]
I was confused about how the UserProfile was implemented.  I understand it now.
I thought that the User model had something like User.profile used to access the profile.
To get the user profile, you should search for a UserProfile that matches the user model.

**Comment by blreams** [comment]
That is correct. While you can provide your own customizations to the contrib User model, I felt it best if we left that as is and just extended through a separate UserProfile model. The UserProfile model contains a link back to the User model.

**Comment by blreams** [comment]
I'm going to close this Issue. I think the original concern is addressed.
