### ISSUE TITLE
Superusers separate from users

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#43]
Do you plan to link superusers (i.e. admins) to players in the pool or will a admin user have 2 login names?  1 for superuser activities and 1 for normal participation in the pool (linked to a player).

Having 2 logins would probably be more secure (separation of privilege principle).  An admin user doesn't need superuser access to make picks, view pages, etc.  The admin user only needs superuser privileges when performing admin functions (like linking a player, locking scores, setting up a week, etc.).  However, having 2 logins is less usable (have to remember 2 usernames and passwords).

Do you have any thoughts?

**Comment by blreams** [comment]
I've been thinking all along that commissioners (ie. admins) would have a separate login from their pool player persona even though it is more baggage. That being said, there is no need for a commissioner login to have a UserProfile.

**Comment by jbholden** [comment]
I think this is reasonable.  I'm closing the issue.
