### ISSUE TITLE
How does a commissioner create new weekly picks?

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#44]
If we get pressed for time before the season starts, we could manage this via the admin interface, though that is far from ideal. I'm adding this Issue as a placeholder because this is something that still needs to be implemented.

**Comment by jbholden** [comment]
I believe the following tasks need to be done
* create a new Week instance (ensure pick deadline set)
* create 10 Games instances (i.e. pick the games)
* optionally create Picks for every player (see #47)

There is also a possible issue with the order that this is done (see #48)

**Comment by blreams** [comment]
I believe that this issue has been addressed with the changes to the Week model (adding pick_deadline and changing the behavior of lock_picks. Additionally, those changes have been incorporated into the createweek and editweek URLs as well as unit and functional tests.
