### ISSUE TITLE
How does a Player submit weekly picks?

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#45]
This is one of the last major pieces that MUST be implemented before the pool season starts. Without this, we would have to continue doing something like last year where we continue with the spreadsheet and parsing functions. Nobody wants that. I'm adding this Issue as a placeholder because I am certain there will be some discussion about it.

**Comment by jbholden** [comment]
I had some time the last few weeks so I did some work on an enter picks page, but it is not quite ready yet.

I was thinking about generating a spreadsheet from each players picks from the website or just filling in the master spreadsheet with the picks after the pick deadline.  This would allow us to verify that the website results match the spreadsheet results.  How much trouble is it to setup the spreadsheets?  Or do you think that the website will be good enough?

**Comment by blreams** [comment]
I was planning on setting up the spreadsheet for the very reason you said, so we could use it to check that the results are the same.

**Comment by blreams** [comment]
If you feel that this issue has been fully addressed with the picks URL, then you should close this issue.
