### ISSUE TITLE
Sequence used to create a new week

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#48]
Right now, the trigger to enter picks is when there are games for a week and before the pick deadline. (reference:  pick10/database.py get_pool_state() function)

This creates a small boundary case when the following sequence is used to create a week.
```
step 1:  create week
step 2:  create 10 games
# at this point, picks are enabled
step 3:  create picks for every player  

# if a player tries to enter picks during step 3, it might get overwritten with a default
``` 

I think the following sequence might work, but probably need to test it
```
step 1:  create week (with lock_picks=None)
step 2:  create 10 games
step 3:  create picks for every player
step 4:  set Week.lock_picks deadline
```

A better solution might be to add a enter_picks boolean field to the Week instance and use that field to trigger the enter picks phase.

**Comment by blreams** [comment]
In step 1, instead of setting lock_picks = None, why not lock_picks = datetime.now()? Then in step 4, you can set lock_picks = deadline.

**Comment by blreams** [comment]
Given that we are going to have separate fields in the Week model for pick_deadline and lock_picks, the updated sequence should be:

```
step 1: create week (use createweek URL with lock_picks=True)
step 2: create 10 games (use editweek URL)
step 3: create default picks for every player
step 4: set Week.lock_picks=False, Week.pick_deadline=deadline_datetime
```

**Comment by jbholden** [comment]
The way the code is currently written, I think you need to set the pick deadline in step 1.
After there are 10 games, the picks are only hidden if it is before the pick deadline.
You could set it to some dummy value in the future, and then change it to the right time in step 4.

Current code
```Python
# pick10/database.py  get_pool_state()
        if week_has_no_games:
            return "week_setup"

        if self.__before_pick_deadline(week):
            if week.lock_picks:
                return "week_setup"
            else:
                return "enter_picks"
```

I could change this behavior if you think it is better to ignore the pick deadline.  

My thinking is that even if the picks are locked, at some point it doesn't matter.  So in this case, after the pick deadline, it doesn't matter if the picks are locked any more.  You won't be able to make any more picks because the deadline has passed.

**Comment by blreams** [comment]
I think the code is OK as it is. When the commissioner POSTs the createweek URL, the result is that the corresponding Week object is created w/ lock_picks == True. In that temporary state before the editweek URL is POSTed, there are no games, so the state returned will be "week_setup".

Once the editweek URL is POSTed, that is when pick_deadline is set (I'll probably add some validation that won't let you clear lock_picks without setting a valid pick_deadline).

The question I have is what does self.__before_week_deadline(week) return if pick_deadline has not been set?

There are some additional steps that the commissioner must undertake for the first week of the year:
```
  1. There must be a registered User for each Player.
  2. Those Users must have UserProfiles that link the User to a Player.
  3, All paid Players must have a PlayerYear.
```

**Comment by jbholden** [comment]
self.__before_week_deadline(week) returns False if the pick deadline has not been set.  This is because for past weeks in the historical data, it is expected that the pick deadline won't be set so it is not before the pick deadline.

**Here is a post I was writing right before I saw your reply:**

Actually, I think the sequence you specified might work.  When you set lock_picks=True in step 1, this will prevent any picks from being entered on the "entered picks" page.

```
step 1: create week (use createweek URL with lock_picks=True)
step 2: create 10 games (use editweek URL)
step 3: create default picks for every player
step 4: set Week.lock_picks=False, Week.pick_deadline=deadline_datetime
```

The problem is with the player results page showing other player's picks.  Here is what the player results page will show at each step
```
after step 1: players results page shows "week being setup"
after step 2: players results page should show all players picks as default # should be OK
after step 3: players results page shows all players picks as default
after step 4: players results page shows "before pick deadline" error message
```

If you were to set the pick deadline to sometime in the future in step 1, then you would see the following behavior (which is probably better).
```
after step 1: players results page shows "week being setup"
after step 2: players results page shows "week being setup"
after step 3: players results page shows "week being setup"
after step 4: players results page shows "before pick deadline" error message
```

**Comment by blreams** [comment]
Agreed. I just committed a change to master such that a createweek URL POST will set a valid default pick_deadline for the Week object it creates.

I also had a few other changes in flight that were included with that commit. Not sure where to document those, so I'm documenting it here:

One change was to allow you to set an environment variable (COLLEGEFOOTBALLPICK10_DATABASE = 'mysql') to tell django to use mysql instead of sqlite3. Of course you have to do some other setup for mysql to work. Along with that there was a db migration created (apparently, mysql needed some additional init that wasn't necessary for sqlite3 but doesn't break it either).

I also fixed a bug in models.get_createweek_year_week() where the function would cause an exception if the commissioner had manually created a new Year with no new Weeks and then called createweek URL.

**Comment by blreams** [comment]
BTW, the only part of this remaining is the default picks part. But that is discussed in Issue #47. So I am going to close this issue.
