### ISSUE TITLE
Checkbox/Menu in navbar not working

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#49]
In Safari, there is a checkbox that shows up next to the Pick10 in the navbar.

![screen shot 2015-08-15 at 2 33 03 pm](https://cloud.githubusercontent.com/assets/1541768/9290298/f5b302e8-435a-11e5-8ba3-79e050fc859d.png)

In Firefox, this shows up as a menu button.  But when clicking it appears to try to show a menu, but nothing shows up in the menu.

![screen shot 2015-08-15 at 2 35 00 pm](https://cloud.githubusercontent.com/assets/1541768/9290299/f815acde-435a-11e5-921d-380ea3dad27b.png)

I don't fully understand what this is supposed to do.

The 2 screenshots were taken with different branches of code, but should be irrelevant to describe this issue.  That's why the location of the "Logged in as: Brent" is in different spots.

**Comment by blreams** [comment]
I've worked a bit on base.html to put the proper functionality in the navbar. I did this in the userprofileform branch, so you should checkout that branch to see the results.

![image](https://cloud.githubusercontent.com/assets/5880937/9292006/7bc313fc-43ae-11e5-8a5a-ba0d45785d23.png)

![image](https://cloud.githubusercontent.com/assets/5880937/9292015/a713be80-43ae-11e5-8307-a1c9d3248afa.png)

The two images above show the same window at different sizes. As you can see the right side nav links get collapsed into a pulldown button. That was the intention of what I had coded before, but I just didn't do it correctly.

The other thing I want to mention is that I changed what the Pick10 and Home links do. The way it should work is that Pick10 is the "brand" (that is a bootstrap thing) and the link will take you to the URL /pick10/. The Home link will take you to the landing page (/).

Pick10 should be the page that has high level statistics about the pool (perhaps stuff like how many participants, the top 5  on the leaderboard, The featured game for the current week). But the key is that you must be logged in to see that page. If you click Pick10 and are not logged in, it will take you through the login pages.

Home should be the main landing page for the pool. It should have some info about the pool, how to register, what it means to login, etc. And anyone can see the landing page (you don't have to be logged in).

**Comment by blreams** [comment]
I just realized this morning that I had committed and pushed changes to base.html to fix this issue in my branch, but that was after I had generated the pull request...so you probably didn't get those changes. I've since merged those changes into master, and you should see the fix there. I'm going to close the issue. If you have any other problems related to this, you can re-open it.

**Comment by jbholden** [comment]
I tried it out and it looks great
