### ISSUE TITLE
Game spread should be a float

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#5]
The spread for a game has been expressed as halves in the past.  (for example 3.5).
Shouldn't the Game.spread field be a float instead of an int?

It is currently defined as
```
spread = models.IntegerField(default=0) 
```

**Comment by blreams** [comment]
Agreed, this is a bug and should be fixed. Should it be:

`spread = models.FloatField(default=0.0)`
or
`spread = models.DecimalField(default=0.0)`

**Comment by jbholden** [comment]
I think DecimalField would work better.  I think that the number of decimal places should be set to 1 since the spread should always be in halves (0.5 is 1 decimal place) 
```
spread = models.DecimalField(default=0.0, decimal_places=1)
```

**Comment by blreams** [comment]
OK, I fixed this, but in addition to decimal_places, I also had to specify max_digits=4 (surely, we'll never have a spread greater than 999.5, right???).
