### ISSUE TITLE
Add start date to Game model

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#6]
I found it nice to display the game start time on the game result pages for games that have not yet started. This field was called "date" in the google app engine model and was a DateTimeProperty().  

Do we want to add a field to the Game model for the start date?

**Comment by blreams** [comment]
I don't see any problem with adding this as an enhancement to the Game model.

**Comment by blreams** [comment]
I just committed a change to allow setting a 'kickoff' field in the Game model. It is a date/time field and is allowed to be blank/null.
