### ISSUE TITLE
enter_picks page should not have radio buttons for game 10

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#60]
Since game 10 is the tie-break game and we are requiring players to enter scores for each team in game 10, there is no need to have a radio button for selecting a game 10 winner. The selected winner can be determined from the score that was entered vs. the spread on the game.

I'm classifying this as a bug because I don't think we want players to be able to create a conflicting result for game 10.

**Comment by jbholden** [comment]
There is a pull request that fixes this

**Comment by blreams** [comment]
I merged your branch (Issue #67) to master and will close this issue.
