### ISSUE TITLE
Getting a default non-naive datetime for pick deadline based solely on Year/Week

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#62]
I'd like to add one more field to the current Year model. The field I want to add is a date that represents the Saturday of the first week of the pool season. Doing so will allow me to create a function that returns a pick deadline given four pieces of information:

  #. The Year number, optional: default to the current year, example: 2015
  #. The Week number, optional: default to the current week, example: 1, 2, ..., 13)
  #. The day of the deadline, optional: default to Thursday, example: 'Friday'
  #. The time of the deadline, optional: default to 4:00pm, example: 5:30pm

The reason for this function is two-fold. The first use is when importing previous data from the spreadsheets, it can be used to set a realistic pick deadline for each week of picks that is imported. I'd have to manually create a dict of "starting Saturdays" for each year from 1997 to 2014 (in stage_history.py).

The second use is when the createweek URL is posted and a new Week object is created. It can be given the default pick_deadline that the commissioner can change if needed.

**Comment by jbholden** [comment]
I'm ok with this

**Comment by blreams** [comment]
I don't think this is needed anymore. The createweek URL already sets a default pick deadline and the editweek URL allows the commissioner to change the pick deadline. So, I'm going to close this issue as invalid.
