### ISSUE TITLE
sidebar active year is not updating

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#66]
In the image below, you can see from the URL that I have clicked on the 2014 button to show the overall results. But the sidebar is stuck on 2013. Not quite sure how I got into this mode except that I had originally loaded 2014 data, then clicked around on each week to get them in the cache. Then I loaded 2013 data and clicked on each week to get those in the cache. When I clicked on the 2014 button, the results updated as expected, but the sidebar 2013 button was still highlighted.

![image](https://cloud.githubusercontent.com/assets/5880937/9477471/80b70dca-4b40-11e5-9816-0386feb84acf.png)

**Comment by jbholden** [comment]
The problem is that the sidebar is cached in the memcache, but the key name does not take into account the year number.  In overall results it is called "overall_year_sidebar".  In week_results it is called "week_year_sidebar".

**Comment by jbholden** [comment]
I created a pull request to fix this

**Comment by blreams** [comment]
Closing this issue after I merged your branch (Issue #68) to master.
