### ISSUE TITLE
Include player's favorite team in UserProfile

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#76]
Would we like to add a player's favorite team to the UserProfile model?

Some possible uses for it
* Admin could use this info to decide what games to include
  (for example:  ensure each person's favorite team used at least once in the pool for a year)
* The winner of a week could be rewarded by displaying their team's colors on the site
* Histogram could show all the favorite teams for the year 
  (example:  South Carolina might be the most favorite, followed by Clemson, etc.)

We might also want to include the team colors in the Team() model, or have the UserProfile specify their teams colors.

**Comment by blreams** [comment]
I like this idea. And actually, you could always display the Player's team colors on their enter picks page.

Definitely colors should be a property (field) of the Team model. We could also add a logo though we might get into trademark issues.

The UserProfile would need a favorite team field that links to the Team model.

**Comment by jbholden** [comment]
I think something that might work (let me know if I misunderstood the issue) is to pass in the player's color preference and set some javascript variables to that value.  Then within the body of the page (that might be cached), use the value of the javascript variable.

This was a possible solution I came up with for highlighting a logged in user's player row in the overall and weekly results page while keeping only 1 copy of the page in the cache.  I would pass in the logged in player's name that sets a variable.  (This was something I was thinking about doing)

**Comment by blreams** [comment]
That seems like the right thing to do. You've already proven the concept w/ the highlighted player row.

**Comment by jbholden** [comment]
The concept hasn't been proven yet.  This is a solution that I think will work.

**Comment by blreams** [comment]
I created a branch (favorite_team) and a new pull request. I didn't want to commit it to master until you have had a chance to try it out and migrate your local database.

**Comment by blreams** [comment]
Actually, it looks you can seemlessly switch back and forth between this branch and master after migrating, so I am going to commit the pull request to master and close this issue.
