### ISSUE TITLE
Generating excel spreadsheet from week picks

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#77]
I created a branch called excel_picks that generates an excel spreadsheet from the week's picks.  I'm not exactly sure what your requirements are for this sheet, so here is what I've done so far.

**Generate the Spreadsheet**
The file is called excel_picks.py and is located in the base directory.
To run this file:
```
step 1.  You need to add the new packages in requirements.txt
step 2.  python excel_picks.py <year> <week number>

Replace year and week number with your desired year/week.
The result is a file called  "picks_<year>_<week>.xls"
```

**Output**
The output file is just a column for the games and then a column for the picks for each player filled in.
My intention was that this data could be copied to the main spreadsheet and then it would do all the calculations.

Is this data good enough?  What else do you need?

**Defaulters**
Right now, if a player has defaulted it sets all the picks and the game scores to an empty string.
Is this ok?  Or should something else be done?

I know that you usually manually change the defaulters to the lowest score value, but for this use case I don't believe that the results would be available to figure out the lowest score or the winners when generating this sheet.

**Comment by blreams** [comment]
This looks good. It should be a simple matter to cut-n-paste from the generated spreadsheet to the official scoring spreadsheet so we can compare results. You should commit this branch.

**Comment by jbholden** [comment]
Do you think the empty string values will work, or do I need to set the cell so it is empty?  I think there is a way to specify the cell type as empty.

I will go ahead and commit what I have.

**Comment by blreams** [comment]
I think it works to leave it as is w/ empty string values. I generated a sheet and checked to make sure the excel is_blank() function returned TRUE for those empty string cells. It does, so I think we are good.

**Comment by jbholden** [comment]
I'm going to close this issue.
