### ISSUE TITLE
User model needs year and state information

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#8]
The User or UserProfile model needs information indicating what years the user has participated in the pool and the state of the user for that particular year.

**Overview**

The year information is required so that the website knows what players participated in which years.
```
 "years" field indicates what years the user participated in
```
I found in this issue a comment about user state:
https://github.com/jbholden/cdcpool_google/issues/20

```
I was thinking that each player would have a "state" (signed up, paid up, etc.). 
This would help the commissioners to see who has signed up to participate and 
who has actually paid. Then, if they aren't paid, they wouldn't show up in any of 
the reports. Right now each row of the Player table is a player/year, correct? 
So this "state" would only apply to a particular player/year combination.
```

**Implementation Options**

Option 1:  year and state information fields with same index
```
1.  Add a "years" field to the UserProfile (list of integers) which 
    specifies what years a user has participated in
2.  Add a states field to the UserProfile that specifies the state (signed up, paid, etc.).  
     This could be a list of strings where the index matches the index 
     in the "years" field for that year.
```

Option 2:  Dictionary
```
I am not sure that django supports this, but it might be nice to create 
a dictionary with the key being the year that the user is participating in, 
and the value being the state.  JSONField might work for this.
https://github.com/bradjasper/django-jsonfield
```

Option 3:  Multiple models
```
This might be implemented by created a model like the following:
class Year(models.Model)
   user = models.OneToOneField(User)
   year = models.IntegerField()
   state = models.CharField()

And then adding year field to the UserProfile
class UserProfile(models.Model)
   year = models.OneToOneField(Year)
   ... other fields

```

Some other option?

**Comment by blreams** [comment]
Option 3 is probably the most straightforward and does not require anything special to use with django.

Option 1...I tend to dislike solutions like this where there is an implicit tie between separate data structures, in this case the tie is that the indices match between multiple lists.

Option 2...This actually isn't a bad option, IMO, but it does require installing another package.

More about Option 3. I'm trying to think of ways that a view might need to pull information from the Year model. For example, suppose I wanted to get all the Players that participated in a particular year.

```
years = Year.objects.filter(year=year)
users = [year.user for year in years]
# Now you can access the UserProfile for each user in users,
# including getting a handle for the corresponding Player
```

**Comment by blreams** [comment]
I thought of one more reason to use Option 3. One thing that would be good to track is how much money each pooler has netted. Over the years we have had different payouts both for weekly wins and for season finishes. Having a Year model would allow us to store information about the payouts for each year in that table.

**Comment by blreams** [comment]
Actually, that won't work since this Year model has a row for every user for every year that they have participated. I'll open a new issue for the pool payout info.

**Comment by jbholden** [comment]
Option 3 seems like a good implementation, but should a Player model be used instead of a User model?

```Python
class Player(models.Model):
  userprofile = models.OneToOneField(UserProfile, blank=True, null=True)
  public_name = CharField()                    # name showed to not logged in users
  private_name = CharField()                   # name showed to logged in users

class Year(models.Model)
   player = models.OneToOneField(Player)
   year = models.IntegerField()
   state = models.CharField()

# queries
years = Year.objects.filter(year=year)
players_in_year = [year.player for year in years] 
users = [player.userprofile for player in players_in_year]
```

I think the issue should remain open until implemented in code.

**Comment by blreams** [comment]
That's a good point, since every historical player will have a Player row. Not every historical player will have a UserProfile row.

One other thing I want to mention. Every new season as UserProfiles go from registered to active (because they paid their entry fee), we need to make sure to create a new Year row for the Player that corresponds to the UserProfile. Is that confusing or what???

**Comment by jbholden** [comment]
I don't know if we than think of a more elegant way to do this.  Is it possible to store all the information within the UserProfile and get rid of the Player and Year models?  When a user registers, link the user to the UserProfile if he/she played in the past or create a new UserProfile if did not play in the past?

Something like this:
```Python
class UserProfile:
    user = models.OneToOneField(User)   # set to None initially
    company = models.CharField(max_length=50, blank=True)
    preferredtz = models.CharField(max_length=100, null=True, blank=True, choices=tz_choices)
    public_name = CharField()                    # name showed to not logged in users
    private_name = CharField()                   # name showed to logged in users
    years = models.CommaSeparatedIntegerField()  # list of years in pool
    states = models.CommaSeparatedIntegerField()  # state information 1:1 corresponds to years field 

# states field is integer enum that represents something like "unregistered"=0, "signed up"=1, "paid"=2
# example:  years=2010,2011,2012;  states="2,2,1"   (corresponds to "paid","paid","signed up"

# query to figure out all the pool years
weeks = Week.objects.all()
years = set()
for w in weeks:
    years.add(w.week_year)

# query to get all players within the year 2014 (not sure if this works or not)
user_profiles = UserProfile.objects.all()
users_in_year = [ u for u in user_profiles if 2014 in u.years ]
```

Or do you want to stick with models for Player, Year, and some payment information?

**Comment by blreams** [comment]
We need a separate Player model so that you have somewhere to store the information about the user when you import the history from the spreadsheets. The reason for that is twofold:

1. At the point where we load the history, we don't have any registered users (and no UserProfile instances).
2. We wanted to keep the User and UserProfile models specific to users that have registered.

Now, you could create a User/UserProfile for each player in the spreadsheets, but that would violate item 2.

IMO, we should keep Players and Users separate.

When a User registers, we could automatically create a new Player for that User (regardless of whether they have a history). Then at any point in the future, a commissioner can manually replace the fresh Player instance with an existing historical Player, updating the OneToOneField in the UserProfile accordingly. And only a commissioner can do that.

**Comment by jbholden** [comment]
I'm fine with the user/player model

**Comment by blreams** [comment]
I'll be adding a page to the wiki to describe all the relationships of the various models. I'll also describe the helper functions in models.py that can be used to add, get or update models.
