### ISSUE TITLE
Loading database fails because no Teams yet

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#83]
After the favorite team was added to models.py, the following sequence fails.

```
# reset the database
step 1.  remove your db file
step 2.  python manage.py migrate

# error message
django.db.utils.OperationalError: no such table: pick10_team
```

I believe the problem is the following code in pick/models.py
```Python
class UserProfile(models.Model):
   ...
    fav_choices = [(team.id, team.team_name) for team in Team.objects.all()]
```
Initially when there is no database there won't be any Team instances.  The teams don't get loaded until stage_history.py script is run I believe.

**Comment by jbholden** [comment]
One other observation, with the above statement, if you ever add another team to the database in the future, you would have to update every UserProfile favorite_team choices as well.

```
class UserProfile(models.Model):
   ...
   fav_choices = [(team.id, team.team_name) for team in Team.objects.all()]
   ...
   favorite_team = models.ForeignKey('Team', blank=True, null=True, choices=fav_choices)
```

**Comment by blreams** [comment]
Refer to Issue #84. I've fixed this as described there.

**Comment by blreams** [comment]
My previous fix did not address the problem of starting with a fresh database. What I just committed master is a bit of compromise but all of the following now work correctly:
  1. You can delete your database and start from scratch by running migrate with getting the exception related to fav_choices.
  2. A logged-in User can set their UserProfile by clicking on Profile in the navbar. The form does not allow them to change the UserProfile.player field (which is something only a commissioner is allowed to do).
  3. A commissioner can change all fields in any User's UserProfile via the admin interface...BUT, for now the favorite_team field is not a pull-down. The commissioner must enter a team_name, and there is no validation that the string corresponds to an actual Team. Later on, I may correct this by creating a separate commissioner UserProfile form and attach that to the admin by assigning this form class to the UserProfileAdmin class's form attribute.

For now I am closing this issue...Again.
