### ISSUE TITLE
Add timezone preference to UserProfile or User model

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#9]
One of the parameters suggested from the Google cdcpool version was to allow a user to have a timezone preference for displaying date times.  This could be added to the UserProfile model.

See https://github.com/jbholden/cdcpool_google/issues/11

**Comment by blreams** [comment]
I added a preferredtz field to UserProfile and gave it a choices argument so that its value could be selected from US time zones. But for some reason, the admin does not show it as a drop-down list form like it should when choices is used. It also is not enforcing that preferredtz must be one of the elements of choices (IOW, you can put whatever string you want in that box).

If you can figure out what I am doing wrong or what I am not doing...I can't seem to make it work.

**Comment by jbholden** [comment]
How do you run the admin?

**Comment by blreams** [comment]
First you have to create a superuser (run the following command and answer the prompts):$ python manage.py createsuperuser
Next make sure you have applied all DB migrations after doing a git pull to get the latest:$ python manage.py migrate
Then start the development server:$ python manage.py runserver
After that, point your browser to http://localhost:8000/admin
Login as the superuser you just created and...voila
BTW, you can pre-load the DB by running these scripts:$ python stage_models.py$ python stage_history.py
Those scripts are still very much a work-in-progress, but they will get you some real data in the DB.

**Comment by blreams** [comment]
The email didn't translate too well. Here are the steps to use the admin:

1. Get the latest commit.
    * $ git pull

2. Make sure your installed packages are the same as mine.
    * $ pip install -r requirements.txt

3. Create a superuser.
    * $ python manage.py createsuperuser

4. Stage data in the database.
    * $ python stage_models.py
    * $ python stage_history.py

5. Apply db migrations
    * $ python manage.py migrate

6. Run the development server
    * $ python manage.py runserver

7. Point your browser at http://localhost:8000/admin

**Comment by jbholden** [comment]
I believe the problem is that the following code from pick10/models.py creates an empty array for tz_choices because no timezones start with 'Us'
```Python
class UserProfile(models.Model):
    tz_choices = [(tz, tz) for tz in pytz.all_timezones if tz.startswith('Us')]
```

The US timezones start with 'US' (capital S)
```Python
class UserProfile(models.Model):
    tz_choices = [(tz, tz) for tz in pytz.all_timezones if tz.startswith('US')]
```

**Comment by blreams** [comment]
I TOTALLY did not catch that. I can't tell you how many times I recreated that particular list comprehension to make sure I got the values I wanted from all_timezones. It never dawned on me that I mis-typed it in the code. Good catch. Fix committed. Working like it is supposed to.
