### ISSUE TITLE
Proper way to preload memcache

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#92]
What is the proper way to preload memcache after using stage_history to import historical spreadsheet data into the database?

I know that an admin can use the URL pick10/<year>/week/<weeknum>/update

Does that preload the entire year into memcache or only the week specified?
Is there a way to preload all years?

**Comment by jbholden** [comment]
Right now, the only way to do this is to update the memcache 1 week at a time.  You could visit the update page for every week and year (as mentioned above), or open every week results page, overall results page, and tiebreak page in a web browser as both a public and a private user.  

We could do the following to make it easier to preload years
* create a web page similar to what exists now that when visited updates every year
* create a web page similar to what exists now that when visited updates 1 year at a time (visit for every year)
* create a script (similar to stage_history.py) that can be run from the command line that will load the database
* integrate code into stage_history.py that loads the memcache after loading a year/week

Any other options?

**Comment by blreams** [comment]
I think I like the fourth bullet option, integrate code into stage_history.py that loads the memcache...

Is there any reason why you wouldn't want to do that when using stage_history to import history from spreadsheets?

**Comment by jbholden** [comment]
I think integrating it into stage_history will work.  As a side effect, it will take longer for stage_history to run.

**Comment by jbholden** [comment]
This is turning out to be a little more complicated than I expected.  I am going to list the things I need to implement this here so I can get organized.

**Found memcache issue where year sidebar didn't show changes to year numbers**
* change overall results page to compute year sidebar dynamically
* change week results page to compute year sidebar dynamically
* change tiebreak page to compute year sidebar dynamically

**no request parameter when called from stage_history.py**
* change overall results page to store page in memcache with request=None
* change week results page to store page in memcache with request=None
* change tiebreak page to store page in memcache with request=None

**Comment by jbholden** [comment]
Pull request #94 resolves this issue

**Comment by blreams** [comment]
Closing this issue
