### ISSUE TITLE
Add link to Commissioner page to update cache

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#99]
We've determined that the cache can get out of sync with the database when a new Player is added. Would be good to provide a link on the Commissioner page that will update the cache by sending a POST request to http://collegefootballpick10.pythonanywhere.com/pick10/2016/update/overall

**Comment by jbholden** [comment]
Also, after a player has entered their picks, the week results page cache is out of sync.  Players that haven't entered picks have a record of 0-10 on the week results page.  I periodically have been visiting http://collegefootballpick10.pythonanywhere.com/pick10/2016/week/2/update to update the cache.  I also visited that link after the pick deadline.

**Comment by blreams** [comment]
I added a link to the commissioner page for updating the cache. Even though any User can navigate directly to the update cache view, the link is only visible to a commissioner since it is on the commissioner page.
